#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanTimeDirectories
\rm -rf 0
\rm -rf surfaces
\rm -f validationData/*.raw
\rm -rf validationResults
cp -r save 0
