#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

 echo "Running blockMesh application"
 runApplication blockMesh

 echo "Running viscoelasticFluidFoam solver"
 echo "Oldroyd-B model:"
 runApplication $application

 echo "Running stressDifferences application"
 runApplication stressDifferences

 echo "Running sample application"
 runApplication sample

 echo "done!"
