#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
\rm -rf 0
\rm -rf surfaces sets
\rm -f validationData/*.raw
\rm -f validationData/*.xy
\rm -rf validationResults
cp -r save 0
