#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
\rm -rf VTK
\rm -rf 0
\cp -r save 0
\rm -f constant/polyMesh/boundary
\rm -rf constant/polyMesh/sets
