#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name from directory
application="elasticSolidFoam"

\cp -f 0/org/U 0/U
\cp -f 0/org/materials 0/materials
runApplication blockMesh
runApplication setFields
runApplication $application