#!/bin/sh
set -x

wmake libso decompositionMethods

if [ -d "$FOAM_MPI_LIBBIN" ]
then
    (WM_OPTIONS=${WM_OPTIONS}$WM_MPLIB; wmake libso parMetisDecomp)
fi

wmake libso MGridGenGamgAgglomeration

# ----------------------------------------------------------------- end-of-file
