#!/bin/sh

currDir=`pwd`
application=`basename $currDir`
cases="slidingBall"

tutorialPath=`dirname $0`/..
. $WM_PROJECT_DIR/bin/tools/RunFunctions

for case in $cases
do
    (cd $case; runApplication blockMesh)
    (cd $case; rm -rf constant/polyMesh/sets)
    (cd $case; rm -rf constant/polyMesh/*Zones)
    (cd $case; runApplication setSet -batch batch.setSet)
    (cd $case; runApplication setsToZones -noFlipMap)
    (cd $case; runApplication $application)
done

cases="sphereAndBrick"
for case in $cases
do
    (cd $case; runApplication fluent3DMeshToFoam sphereAndBrickFine.msh)
    (cd $case; rm -rf constant/polyMesh/sets)
    (cd $case; rm -rf constant/polyMesh/*Zones)
    (cd $case; runApplication setSet -batch batch.setSet)
    (cd $case; runApplication setsToZones -noFlipMap)
    (cd $case; runApplication $application)
done
