#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="dbnsTurbFoam"

gunzip naca0012.cas.gz
runApplication fluentMeshToFoam naca0012.cas
gzip naca0012.cas
runApplication $application
