#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="icoFoam"

runApplication blockMesh
runApplication potentialFoam -writep
runApplication $application
