#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

if [ -f $CUDA_BIN_DIR/nvcc ] 
then
    if [ -z $CUDA_IGNORE ]
    then
        echo "Found nvcc but \$CUDA_IGNORE set -- not  enabling CUDA support."
    else
        echo "Found nvcc  --  enabling CUDA support."
        wmake libso
    fi 
else
    echo "No nvcc - CUDA not available."
fi

# ----------------------------------------------------------------- end-of-file
