#!/bin/sh

currDir=`pwd`
application=`basename $currDir`
cases="hotCylinder"

tutorialPath=`dirname $0`/..
. $WM_PROJECT_DIR/bin/tools/RunFunctions

for case in $cases
do
    (cd $case; runApplication blockMesh)
    (cd $case; runApplication $application)
done
