#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

if [ "$PWD" != "$WM_PROJECT_DIR" ]
then
    echo "Error: Current directory is not \$WM_PROJECT_DIR"
    echo "    The environment variable are not consistent with the installation."
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
fi

# wmake is required for subsequent targets
( cd wmake/src && make )

# build ThirdParty sources
#( cd $WM_THIRD_PARTY_DIR && ./Allwmake )
# ( cd $WM_THIRD_PARTY_DIR && ./AllMake )

# We make sure the ThirdParty packages environment variables are up-to-date
# before compiling the rest of OpenFOAM
. $WM_PROJECT_DIR/etc/settings.sh

# build OpenFOAM libraries and applications
src/Allwmake
applications/Allwmake

if [ "$1" = doc ]
then
    doc/Allwmake
fi

# ----------------------------------------------------------------- end-of-file
