#!/bin/bash
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo "This tutorial fails in octree search: blame Mattijs Janssens (HJ). Martin Beaudoin, Oct 12 2010"
exit 0;

# Get application name
application=`getApplication`

#parentDir=`dirname $PWD`
#application=`basename $parentDir`

runApplication blockMesh
runApplication $application
