#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

# Clean compilation in Fluid-Structure Interaction package
(
    cd FluidStructureInteraction/src/
    ./Allwclean
)

#Clean makeAxialMesh
wclean MakeAxialMesh/makeAxialMesh

# ----------------------------------------------------------------- end-of-file
