#!/bin/sh
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     |
#   \\  /    A nd           | Copyright held by original author
#    \\/     M anipulation  |
#-------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software; you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by the
#     Free Software Foundation; either version 2 of the License, or (at your
#     option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM; if not, write to the Free Software Foundation,
#     Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#
# Script
#     addCompile
#
# Description
#     Cleans up the dependency list and add the compilation statement.
#     It has to be written in the C-shell rather than the Bourne shell
#     because it uses file name manipulators.
#
#     Usage: wmkdep <fileName> | addCompile <fileName>
#
#------------------------------------------------------------------------------

sourceName=${1##*/}
objectName=${sourceName%.*}.o
className=${sourceName%.*}.class
sub=${1##*.}
depName=${1%.*}.dep

sourceDir=${1%/*}

if [ "$sourceDir" = "$sourceName" ]
then
    sourceDir=.
fi

if [ "$WM_PROJECT_DIR" ]
then
    sed -e s%$WM_PROJECT_DIR%'$(WM_PROJECT_DIR)'% > $depName
else
	cat > $depName
fi


if [ "$sub" = "java" ]
then

    sed -e s%"\(.*\).class.*:"%'$(CLASSES_DIR)/'"\1.class\:"%   \
        -e s%$WM_PROJECT_DIR%'$(WM_PROJECT_DIR)'%               \
        >> $depName

    echo '$(CLASSES_DIR)/'$sourceDir/$className': $(EXE_DEP)' >> $depName
    echo '$(CLASSES_DIR)/'$sourceDir/$className':' >> $depName
    echo '	@SOURCE_DIR='$sourceDir '\' >> $depName
    echo '	SOURCE='$1' ; $('$sub'toclass)' >> $depName

else

    sed -e s%".*.o.*:"%'$(OBJECTS_DIR)/'"$objectName\:"%  \
        -e s%$WM_PROJECT_DIR%'$(WM_PROJECT_DIR)'%         \
        >> $depName

    echo '$(OBJECTS_DIR)/'$objectName': $(EXE_DEP)' >> $depName
    echo '$(OBJECTS_DIR)/'$objectName':' >> $depName
    echo '	@SOURCE_DIR='$sourceDir >> $depName
    echo '	SOURCE='$1' ; $('$sub'too)' >> $depName

fi

#------------------------------------------------------------------------------
