#!/bin/sh
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | foam-extend: Open Source CFD
#  \\    /   O peration     | Version:     4.0
#   \\  /    A nd           | Web:         http://www.foam-extend.org
#    \\/     M anipulation  | For copyright notice see file Copyright
#------------------------------------------------------------------------------
# License
#     This file is part of foam-extend.
#
#     foam-extend is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by the
#     Free Software Foundation, either version 3 of the License, or (at your
#     option) any later version.
#
#     foam-extend is distributed in the hope that it will be useful, but
#     WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#     General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with foam-extend.  If not, see <http://www.gnu.org/licenses/>.
#
# Script
#     makeFiles
#
# Description
#     Scan the current directory for source files and construct Make/files
#
#     Usage : makeFiles
#
#------------------------------------------------------------------------------

if [ -r Make/files ]
then
    echo "makeFiles: Make/files already exists, exiting"
    exit 1
fi

bin=$WM_DIR/bin/$WM_ARCH$WM_COMPILER

[ -d Make ] || mkdir Make
rm -f Make/files

dirs=`find . -name "*" -type d -print`

for dir in $dirs
do
    if [ $dir != . ]
    then
        baseDir=`echo $dir | sed 's%^\./%%'`
        baseDirName=`echo $baseDir | $bin/dirToString`

        if [ $baseDirName != Make ]
        then
            echo $baseDirName " = " $baseDir >> Make/files
        fi
    fi
done

echo >> Make/files

files=`find . -name "*.[cCylfF]" -type f  -print`

for file in $files
do
    pathName=`echo ${file%/*} | sed 's%^\.%%' | sed 's%^/%%' | $bin/dirToString`
    fileName=`echo ${file##*/}`

    if [ "$pathName" != "" ]
    then
        echo '$('$pathName')/'$fileName >> Make/files
    else
        echo $fileName >> Make/files
    fi
done

echo >> Make/files

echo 'EXE = $(FOAM_APPBIN)/'${PWD##*/} >> Make/files

#------------------------------------------------------------------------------
