#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="laplacianFoam"

\cp -f blockMeshDict constant/polyMesh/blockMeshDict
runApplication blockMesh

runApplication decomposePar -cellDist
runParallel $application 2
