#!/bin/bash
#
#set -x

. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Load additional RunFunctions
. ./RunFunctionsSupplemental

export caseName=`basename $PWD`

#We stop this script when we encounter a problem
#trap "exit -1" ERR

echo "$caseName: Running blockMesh"
runApplicationAndReportOnError blockMesh

echo "$caseName: Creating zones for the mixingPlane"
runApplicationAndReportOnError setSet -batch setBatch
runApplicationAndReportOnError setsToZones -noFlipMap

echo "$caseName: Creating the starting time directory"
cp -r 0_orig 0

echo "$caseName: Running laplacianFoam"
runApplicationAndReportOnError laplacianFoam



