#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="icoIbFoam"

compileApplication refineThickPlateMesh

mkdir constant/polyMesh
cp -f save/blockMeshDict constant/polyMesh

runApplication blockMesh
cp -f save/boundary constant/polyMesh/

runApplication refineThickPlateMesh

# \rm -rf constant/polyMesh
# \mv 0/polyMesh constant/polyMesh

\rm -rf 0
\mkdir 0
\cp 0_org/* 0/

runApplication potentialIbFoam
runApplication $application
