#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name from directory
application="icoFsiElasticNonLinULSolidFoam"

cd fluid;
runApplication fluent3DMeshToFoam fluid.msh
runApplication changeDictionary
runApplication setSet -batch batch.setSet
runApplication setsToZones -noFlipMap
runApplication decomposePar

cd ../solid;
runApplication fluent3DMeshToFoam solid.msh
runApplication changeDictionary
runApplication setSet -batch batch.setSet
runApplication setsToZones -noFlipMap
runApplication decomposePar

cd ..
./makeLinks fluid solid

(cd fluid; runParallel $application 2)
