#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application="liquidFilmFoam"

\cp -f ./0/h.org ./0/h

runApplication blockMesh
runApplication makeFaMesh
compileApplication setInitialDroplet
runApplication setInitialDroplet
runApplication $application
