#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

runApplication -l log.blockMesh.solid blockMesh -case ../solid
runApplication -l log.setSet.solid setSet -case ../solid -batch ../solid/setBatch
runApplication -l log.setToZones.solid setsToZones -case ../solid -noFlipMap

runApplication blockMesh
runApplication setSet -batch setBatch
runApplication setsToZones -noFlipMap

cd ..

# Build setInletVelocity function object
wmake libso setInletVelocity

./makeSerialLinks fluid solid

cd fluid

runApplication $application

# ----------------------------------------------------------------- end-of-file
