#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

runApplication -l log.blockMesh.solid blockMesh -case ../solid
runApplication -l log.setSet.solid setSet -case ../solid -batch ../solid/setBatch
runApplication -l log.setToZones.solid setsToZones -case ../solid -noFlipMap

runApplication -l log.decomposePar.solid decomposeParFsi -case ../solid -cellDist

runApplication blockMesh
runApplication setSet -batch setBatch
runApplication setsToZones -noFlipMap

runApplication decomposeParFsi -cellDist

cd ..

./makeLinks fluid solid

# Build setInletVelocity function object
wmake libso setInletVelocity

cd fluid

runParallel $application 8

# ----------------------------------------------------------------- end-of-file
