#!/bin/bash
# /*---------------------------------------------------------------------------*\
#   =========                 |
#   \\      /  F ield         | foam-extend: Open Source CFD
#    \\    /   O peration     |
#     \\  /    A nd           | For copyright notice see file Copyright
#      \\/     M anipulation  |
# -------------------------------------------------------------------------------
# License
#     This file is part of foam-extend.
#
#     foam-extend is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by the
#     Free Software Foundation, either version 3 of the License, or (at your
#     option) any later version.
#
#     foam-extend is distributed in the hope that it will be useful, but
#     WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#     General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with foam-extend.  If not, see <http://www.gnu.org/licenses/>.
#
# Description
#        Allrun file for running the FOAM Turbomachinery OSIG test harness
#
# Author
#        Martin Beaudoin, Hydro-Quebec, 2010. All rights reserved
#
# \*---------------------------------------------------------------------------*/

#set -x

# Environment variable : BREEDER_15_DIR:
#
# This environment variable must point to the location of the Breeder_1.5 section
# of your local working copy of the openfoam-extend Subversion repository
#
# Something like this:
#
# export BREEDER_15_DIR=/someAbsolutePath/Breeder_1.5

export BREEDER_OSIG_TURBOMACHINERY_DIR=${BREEDER_15_DIR}/OSIG/TurboMachinery

# This environment variable must point to the location of the test harness main directory
export FOAM_TEST_HARNESS_DIR=$(dirname $PWD)

# First, some sanity checks
#

# We need $BREEDER_15_DIR
if [ ! -n "${BREEDER_15_DIR}" ]
then
    echo "Warning:"
    echo "  Missing environment variable \$BREEDER_15_DIR. Stopping."
    echo "  Please make sure to initialize this environment variable to "
    echo "  the directory where you have installed the Breeder_1.5 section "
    echo "  of the openfoam-extend Subversion repository"
    exit -1
fi

# We need $WM_PROJECT_DIR
if [ -z "$WM_PROJECT_DIR" ]
then
    echo "Warning:"
    echo "  Missing environment variable \$WM_PROJECT_DIR. Stopping."
    echo "  Please make sure your FOAM environment is properly set up."
    exit -1
fi

# We need $
if [ ! -e $BREEDER_OSIG_TURBOMACHINERY_DIR/CMakeLists.txt ]
then
    echo "Warning:"
    echo "  Missing file: CMakeLists.txt under \$BREEDER_15_DIR/OSIG/TurboMachinery. Stopping."
    echo "  A copy of CMakeLists.txt is available under $FOAM_TEST_HARNESS_DIR/CMakeFiles."
    echo "  Please make a copy of this file under the directory \$BREEDER_15_DIR/OSIG/TurboMachinery."
    exit -1
fi

# We also need $BREEDER_OSIG_TURBOMACHINERY_DIR/CTestConfig.cmake
if [ ! -e $BREEDER_OSIG_TURBOMACHINERY_DIR/CTestConfig.cmake ]
then
    echo "Warning:"
    echo "  Missing file: CTestConfig.cmake under \$BREEDER_OSIG_TURBOMACHINERY_DIR. Stopping."
    echo "  A copy of CTestConfig.cmake for openfoam-extend is available under $FOAM_TEST_HARNESS_DIR/CMakeFiles."
    echo "  For a copy of CTestConfig.cmake for your local CDash server, contact your local CDash admin."
    echo "  Please make a copy of this file under \$BREEDER_OSIG_TURBOMACHINERY_DIR/CTestConfig.cmake."
    exit -1
fi

# Make sure the CMake and tutorials runtime files are updated
# We need cmake version 2.8.0 at least
cmake $BREEDER_OSIG_TURBOMACHINERY_DIR

# All set. Now we can run the available test harness
#
# Invoke make help for the complete list of available commands.
#
# User-demand testing.
# Will do: ExperimentalConfigure + ExperimentalBuild + ExperimentalTest + ExperimentalSubmit
make Experimental

# Nightly testing
# Will do: NightlyUpdate + NightylConfigure + NightlyBuild + NightlyTest + NightlySubmit
# make Nightly

# That's it
