#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanTimeDirectories
\rm -rf 0
\rm -rf surfaces
\rm -rf forces
\rm -f *raw
\rm -rf logs nohup.out
\rm -rf postProcessing

cp -r save 0
