#----------------------------------*-sh-*--------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     |
#   \\  /    A nd           | Copyright held by original author
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software; you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by the
#     Free Software Foundation; either version 2 of the License, or (at your
#     option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM; if not, write to the Free Software Foundation,
#     Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#
# Script
#     paraview/bashrc
#
# Description
#     Setup file for Paraview.
#     Sourced from OpenFOAM-?.?/etc/bashrc
#
#------------------------------------------------------------------------------

export CMAKE_HOME=$WM_THIRD_PARTY_DIR/cmake-2.4.6/platforms/$WM_ARCH

if [ -r $CMAKE_HOME ]; then
    export PATH=$CMAKE_HOME/bin:$PATH
else
    unset CMAKE_HOME
fi

export ParaView_VERSION=2.4.4

export ParaView_INST_DIR=$WM_THIRD_PARTY_DIR/ParaView$ParaView_VERSION
export ParaView_DIR=$ParaView_INST_DIR/lib/paraview-2.4

if [ "$PYTHONPATH" ]; then
    export PYTHONPATH=$PYTHONPATH:$ParaView_DIR/Utilities/VTKPythonWrapping
else
    export PYTHONPATH=$ParaView_DIR/Utilities/VTKPythonWrapping
fi

if [ -r $ParaView_INST_DIR ]; then
    export PV_INTERFACE_PATH=$FOAM_UTILITIES/postProcessing/graphics/PVFoamReader/PVFoamReader/Make

    export PATH=$ParaView_INST_DIR/bin:$PATH
    export LD_LIBRARY_PATH=${ParaView_INST_DIR}/lib:${ParaView_INST_DIR}/lib/vtk:${LD_LIBRARY_PATH}
    export PV_PLUGIN_PATH=$FOAM_LIBBIN
fi

if [ -r $ParaView_DIR ]; then
    export VTK_DIR=$ParaView_DIR/VTK
fi

# -----------------------------------------------------------------------------
