#!/bin/bash
#
#set -x

. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Load additional RunFunctions
. ./RunFunctionsSupplemental

export caseName=`basename $PWD`

#We stop this script when we encounter a problem
#trap "exit -1" ERR

echo "$caseName: Creating the file blockMeshDict using m4"
(cd constant/polyMesh; m4 -P blockMeshDict.m4 > blockMeshDict)

echo "$caseName: Running blockMesh"
runApplicationAndReportOnError blockMesh

echo "$caseName: Updating the GGI and mixingPlane interfaces parameters"

# Let's see if pyFoamChangeMixingPlaneBoundary.py is available
command -v pyFoamChangeMixingPlaneBoundary.py >/dev/null
if [ $? -eq 0 ];
then
    echo "Using pyFoamChangeMixingPlaneBoundary.py"
    pyFoamChangeMixingPlaneBoundary.py . B_UPSTREAM   \
	--shadowPatch                    B_DOWNSTREAM \
	--coordinateSystemType           cylindrical  \
	--coordinateSystemOrigin         "(0 0 0)"    \
	--coordinateSystemE1             "(1 0 0)"    \
	--coordinateSystemE3             "(0 0 1)"    \
	--assembly                       both         \
	--orientation                    dirR_spanTheta

    pyFoamChangeMixingPlaneBoundary.py . B_DOWNSTREAM \
	--shadowPatch                    B_UPSTREAM   \
	--coordinateSystemType           cylindrical  \
	--coordinateSystemOrigin         "(0 0 0)"    \
	--coordinateSystemE1             "(1 0 0)"    \
	--coordinateSystemE3             "(0 0 1)"    \
	--assembly                       both         \
	--orientation                    dirR_spanTheta

    echo "Using pyFoamChangeGGIBoundary.py"
    pyFoamChangeGGIBoundary.py . sideWallA_BB_cyclic1   \
	--shadowPatch            sideWallA_BB_cyclic2   \
	--rotationAxis           "(0 0 1)"              \
	--rotationAngle          60                     \
	--zone                   sideWallA_BB_cyclic1Zone

    pyFoamChangeGGIBoundary.py . sideWallA_BB_cyclic2   \
	--shadowPatch            sideWallA_BB_cyclic1   \
	--rotationAxis           "(0 0 1)"              \
	--rotationAngle          -60                    \
	--zone                   sideWallA_BB_cyclic2Zone

else
    echo "pyFoamChangeMixingPlaneBoundary.py is missing. Using the file constant/polyMesh/boundary.preconfigured"
    cp constant/polyMesh/boundary.preconfigured constant/polyMesh/boundary
fi

echo "$caseName: Creating the starting time directory"
cp -r 0_orig 0

runApplication setSet -batch setBatchGgi
runApplication setsToZones -noFlipMap

echo "$caseName: Running laplacianFoam"
runApplicationAndReportOnError laplacianFoam

