#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="icoDyMSimpleFoam"

runApplication blockMesh
runApplication setSet -batch setBatch

cd constant/polyMesh/sets/
\rm -f leftCentre leftCentre_old leftWallSet leftWallSet_old leftZone_old rightCentre rightCentre_old rightWallSet rightWallSet_old rightZone_old wallSet
\rm -f leftCentre.gz leftCentre_old.gz leftWallSet.gz leftWallSet_old.gz leftZone_old.gz rightCentre.gz rightCentre_old.gz rightWallSet.gz rightWallSet_old.gz rightZone_old.gz wallSet.gz
cd ../../..

runApplication setsToZones
#runApplication decomposePar
runApplication $application
#runParallel $application 4
#runApplication reconstructParMesh -cellDist
