#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
\rm -rf .setSet 0/cellDist 0/cellDist.gz constant/cellDecomposition 
\rm -rf *.vtk
\rm -rf constant/polyMesh/
\rm -rf 0 holeTri*
cp -r save 0
