#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="interOversetFoam"

\rm -rf 0
cp -r save 0
mkdir constant/polyMesh
\cp -f blockMeshDict constant/polyMesh/blockMeshDict
runApplication blockMesh
\cp -f boundary constant/polyMesh/boundary
runApplication setSet -batch setBatch.batch
\rm -f constant/polyMesh/sets/*_old constant/polyMesh/sets/*_old.gz

\mv 0/alpha1.org 0/alpha1
runApplication setFields

#runApplication $application

runApplication decomposePar -cellDist
runApplication decomposeSets -writeEmptySets
runParallel $application 4

