#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
application="laplacianFoam"

runIdeasToFoam ()
{
    if [ -f log.ideasToFoam ] ; then
        echo "ansysToFoam already run on $PWD: remove log file to run"
    else
        echo "ansysToFoam: converting mesh $1"
        ansysToFoam $1 -scale $2 > log.ansysToFoam 2>&1
    fi
}

runIdeasToFoam flange.ans 0.001
runApplication $application
runApplication foamToFieldview9
runApplication foamToEnsight
