#!/bin/sh -x

cd $1/constant

ln -sf ../../$2/constant solid
cd ../system
ln -sf ../../$2/system solid
cd ../0
ln -sf ../../$2/0 solid
cd ..

for proc in processor*; do
cd $proc
cd 0
ln -sf ../../../$2/$proc/0 solid
cd ../constant
ln -sf ../../../$2/$proc/constant solid
cd ../..
done
