#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name from directory
application="icoDyMFoam"

compileApplication setMotionMovingCone
runApplication blockMesh
runApplication setMotionMovingCone
runApplication $application
