#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

# Compile the MRFInterfoam application
wmake ../$application
wclean ../$application

# Now run the tutorial case
runApplication ./makeMesh
runApplication $application
