#! /usr/bin/env zsh
#----------------------------------*-sh-*--------------------------------------
# =========                 |
# \\      /  F ield         | foam-extend: Open Source CFD
#  \\    /   O peration     |
#   \\  /    A nd           | For copyright notice see file Copyright
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
# License
#     This file is part of foam-extend.
#
#     foam-extend is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by the
#     Free Software Foundation, either version 3 of the License, or (at your
#     option) any later version.
#
#     foam-extend is distributed in the hope that it will be useful, but
#     WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#     General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with foam-extend.  If not, see <http://www.gnu.org/licenses/>.
#
# Script
#     etc/zshrc
#
# Description
#     Startup file for OpenFOAM
#     Sourced from ~/.login or ~/.cshrc
#
#------------------------------------------------------------------------------

if ( $?FOAM_SOURCED_FROM_ALIAS ) then
    # Sourced from an alias
    set sourced=($_)
    shift sourced

    set thisScript=$FOAM_SOURCED_FROM_ALIAS

    # Clear the variable to make sure regular sourcing still works
    unsetenv FOAM_SOURCED_FROM_ALIAS
else
    # regular sourcing
    set sourced=($_)
    set thisScript=($sourced[2])

    shift sourced
    shift sourced
endif

set thisDir=`python -c "from os.path import *;import sys;sys.stdout.write(dirname(abspath(join(curdir,'$thisScript'))))"`

$thisDir/getVariables.py tcsh $sourced | source /dev/stdin

unset thisScript thisDir sourced

# -----------------------------------------------------------------------------
