#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cd PTT-Exponential
    cleanCase

cd ..
cd DCPP
    cleanCase

cd ..
cd Giesekus
    cleanCase


cd ..
cd FENE-CR
    rm -rf constant/polyMesh/sets > /dev/null 2>&1
    cleanCase

cd ..
cd FENE-P
    cleanCase

cd ..
cd Feta-PTT
    cleanCase

cd ..
cd Leonov
    cleanCase

cd ..
cd Oldroyd-B
    cleanCase

cd ..
cd PP
    cleanCase

cd ..
cd PTT-Linear
    cleanCase

cd ..
cd White-Metzner/Carreau-Yasuda
    cleanCase

cd ../..
cd XPP_DE
    cleanCase

cd ..
cd XPP_SE
    cleanCase

cd ..

