#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="viscoelasticFluidFoam"

cd FENE-CR

    runApplication gmshToFoam mesh.msh
    cp boundary constant/polyMesh/boundary
    echo "FENE-CR: execution time ~ 320 s in a Core 2 Duo 2.0 Ghz processor"
    runApplication $application

cd ..
cd PTT-Exponential
    runApplication blockMesh
    echo "PTT-Exponential: execution time ~ 4250 s in a Core 2 Duo 2.0 Ghz processor"
    runApplication $application


cd ..
cd DCPP

    runApplication blockMesh
    echo "DCPP: execution time ~ 41830 s in a Core 2 Duo 2.0 Ghz processor"
    runApplication $application
    runApplication PSD
    runApplication sample

cd ..
cd Giesekus

    runApplication blockMesh
    echo "Giesekus: execution time ~ 91195 s in a Core 2 Duo 2.0 Ghz processor"
    runApplication $application
    runApplication stressDifferences

cd ..
