#!/bin/bash
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application from system/controlDict
application=`getApplication`

runApplication blockMesh
runApplication $application
