#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="conjugateHeatFoam"

runApplication blockMesh
cp boundary constant/polyMesh

cd ../heatedBlock
runApplication blockMesh
cp boundary constant/polyMesh

cd ../conjugateCavity
runApplication $application

