#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="conjugateHeatFoam"

runApplication blockMesh
cp boundary constant/polyMesh
runApplication setSet -batch setBatch
runApplication setsToZones -noFlipMap

cd ../heatedBlock
runApplication blockMesh
cp boundary constant/polyMesh
runApplication setSet -batch setBatch
runApplication setsToZones -noFlipMap

cd ../conjugateCavity
runApplication $application

