#!/bin/sh

application="conjugateHeatFoam"
cases="conjugateCavity"

tutorialPath=`dirname $0`/..
. $WM_PROJECT_DIR/bin/tools/RunFunctions

for case in $cases
do
    runApplication $application
done 

