#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name from directory
application="elasticOrthoSolidFoam"

\cp 0/org/U 0/org/materials 0/org/materialDirections 0/
runApplication blockMesh
runApplication setFields
runApplication $application