#!/bin/bash
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

\cp -f boundary constant/polyMesh/boundary
\rm -rf 0
\cp -r save 0
runApplication setSet -batch setBatch.batch
runApplication setsToZones -noFlipMap
runApplication potentialFoam
runApplication simpleFoam


