#!/bin/sh

( cd channelSimpleOverlapicoOversetFoam ; ./Allclean )
( cd cylinderInChannelicoOversetFoam ; ./Allclean )

( cd staticCylinderSheddingTest ; ./Allclean )
( cd navyCylinderSheddingTest ; ./Allclean )
