#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="icoDyMFoam"

runApplication blockMesh
cp boundary constant/polyMesh
runApplication setSet -batch setBatch
runApplication setsToZones -noFlipMap
runApplication $application
