#!/bin/sh
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     |
#   \\  /    A nd           | Copyright held by original author
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software; you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by the
#     Free Software Foundation; either version 2 of the License, or (at your
#     option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM; if not, write to the Free Software Foundation,
#     Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#
# Script
#     wcleanAlmostAll
#
# Description
#     script that searches all the directories below the current for the
#     object file directories of all machines and then deletes them.
#
#------------------------------------------------------------------------------

if [ ! -d bin -o ! -d src ]
then
   echo $0: not in the project top level directory !
   exit 1
fi


for dir in lib applications/bin
do
   if [ -d $dir ]
      rm -rf $dir/*
   fi
done

( cd tutorials && ./Allclean )

# find . -name '*~' -exec rm {} \;
find . -name '*.dep' -exec rm {} \;

find `find . -depth \( -name "Make[.A-Za-z]*" -o -name "Make" \) -type d -print` -depth \( -type d ! -name "*Make[.A-Za-z]*" ! -name "*Make" \( ! -path '*.svn*' \) \) -exec rm -r {} \;

find . -depth -type d \( -name lnInclude -o -name ii_files -o -name Templates.DB \) -exec rm -rf {} \;

find . \( -name exe -o -name log -o -name so_locations \) -exec rm {} \;

#------------------------------------------------------------------------------
