#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication surfaceFeatureEdges 5415Joined2.stl 5415Joined3.ftr

runApplication cartesianMesh
runApplication checkMesh
