#!/bin/sh

currDir=`pwd`
application=`basename $currDir`
cases="springDamper sixDOFmotion"

tutorialPath=`dirname $0`/..
. $WM_PROJECT_DIR/bin/tools/RunFunctions

for case in $cases
do
    runApplication $application $case
done
