#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanTimeDirectories
cleanCase
\rm -rf constant/polyMesh/sets constant/polyMesh/*Zones*
\rm -rf VTK case.foam history normalContact_*.txt frictionContact_*.txt
