#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory
set -x

if [ -d "$PARAVIEW_DIR" -a -r "$PARAVIEW_DIR" ]
then
   case "$PARAVIEW_VERSION" in
   3*)
      wmake libso vtkPV3Foam
      (
         cd PV3FoamReader
         mkdir -p Make/$WM_OPTIONS > /dev/null 2>&1
         cd Make/$WM_OPTIONS
         cmake ../..
	 if [ "$WM_ARCH_BASE" == "darwin" ]
	 then
	     sed -i bak -e 's/-dynamiclib /& -undefined dynamic_lookup /' CMakeFiles/PV3FoamReader.dir/link.txt	 
	     sed -i bak -e 's/-dynamiclib /& -undefined dynamic_lookup /' CMakeFiles/PV3FoamReader_SM.dir/link.txt	 
	 fi
         make
      )
      ;;
   esac
fi

# ----------------------------------------------------------------- end-of-file
