#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

\rm -f constant/cellDecomposition.gz

\rm -rf constant/polyMesh/*
\cp save/blockMeshDict constant/polyMesh/

\rm -rf 0
