#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="simpleIbFoam"

runApplication blockMesh
cp save/boundary constant/polyMesh

\mkdir 0
\cp 0_org/* 0/

runApplication potentialIbFoam
runApplication $application
