#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso dynamicMesh

# Make meshMotion solvers
meshMotion/Allwmake

wmake libso dynamicFvMesh
wmake libso topoChangerFvMesh

# ----------------------------------------------------------------- end-of-file
