#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso dynamicMesh

# Make meshMotion solvers
meshMotion/Allwmake

# Make libraries in dynamicFvMesh
dynamicFvMesh/Allwmake

wmake libso topoChangerFvMesh

# ----------------------------------------------------------------- end-of-file
