#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso autoMesh
wmake libso blockMesh
wmake libso extrudeModel
wmake libso cfMesh

# ----------------------------------------------------------------- end-of-file
