#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso decomposeReconstruct

wmakeLnInclude decompositionMethods

wmake libso decompositionMethods
wmake libso metisDecomp
wmake libso parMetisDecomp
wmake libso scotchDecomp


# ----------------------------------------------------------------- end-of-file
