#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="MRFSimpleFoam"
#application="simpleFoam"

#Create the mesh:
./makeMesh

# Set 0-directory and create GGI set:
cp -r 0_orig 0
setSet -batch setBatchGgi
setsToZones -noFlipMap

#Fix constant/boundary:
cp system/changeDictionaryDict_mixingPlane system/changeDictionaryDict
changeDictionary

#Pick settings:
cp system/fvSolution_mixingPlane system/fvSolution

runApplication $application
