#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application="liquidFilmFoam"

runApplication blockMesh
runApplication makeFaMesh
runApplication $application
