#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r 0-orig 0
runApplication blockMesh
runApplication setSet -batch createObstacle.setSet
runApplication subsetMesh c0 -patch walls -overwrite
runApplication setFields
runApplication interDyMFoam
