#!/bin/sh
set -x

wmake libso fluidSolidInteraction

# Create Eigen soft link
ln -srf ../../../ThirdParty/packages/eigen3/Eigen/ fluidSolidInteraction/lnInclude/

wmake solvers/fsiFoam
wmake solvers/ampFsiFoam
wmake solvers/weakFsiFoam
wmake solvers/fluidFoam
wmake solvers/solidFoam
wmake solvers/thermalSolidFoam

wmake libso utilities/functionObjects/pointHistory
wmake libso utilities/functionObjects/patchAvgTractionHistory
wmake libso utilities/functionObjects/centrifugalBodyForce
