#----------------------------------*-sh-*--------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     |
#   \\  /    A nd           | Copyright held by original author
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software; you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by the
#     Free Software Foundation; either version 2 of the License, or (at your
#     option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM; if not, write to the Free Software Foundation,
#     Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#
# Script
#     paraview3/bashrc
#
# Description
#     Setup file for ParaView3.
#     Sourced from OpenFOAM-?.?/etc/bashrc
#
#------------------------------------------------------------------------------

export CMAKE_HOME=$WM_THIRD_PARTY_DIR/cmake-2.4.6/platforms/$WM_ARCH

if [ -r $CMAKE_HOME ]; then
    export PATH=$CMAKE_HOME/bin:$PATH
else
    unset CMAKE_HOME
fi

export ParaView_VERSION="3.3-cvs"
# export ParaView_VERSION="3.4.0"

export ParaView_INST_DIR=$WM_THIRD_PARTY_DIR/ParaView-$ParaView_VERSION
export ParaView_DIR=$ParaView_INST_DIR/platforms/$WM_ARCH$WM_COMPILER

if [ "$PYTHONPATH" ]; then
    export PYTHONPATH=$PYTHONPATH:$ParaView_DIR/Utilities/VTKPythonWrapping
else
    export PYTHONPATH=$ParaView_DIR/Utilities/VTKPythonWrapping
fi
if [ $WM_ARCH == "darwinPpc" -o $WM_ARCH == "darwinIntel" ]	    
then
    export PYTHONPATH=$PYTHONPATH:$ParaView_DIR/bin
fi

if [ -r $ParaView_DIR ]; then
    export PATH=$ParaView_DIR/bin:$PATH
    export LD_LIBRARY_PATH=$ParaView_DIR/bin:$LD_LIBRARY_PATH
    if [ $WM_ARCH == "darwinPpc" -o $WM_ARCH == "darwinIntel" ]	    
    then
	export DYLD_LIBRARY_PATH=$ParaView_DIR/bin:$DYLD_LIBRARY_PATH
	export PV_PLUGIN_PATH=$FOAM_LIBBIN/paraview
	if [ ! -e $PV_PLUGIN_PATH ]
	then
	    echo "Creating $PV_PLUGIN_PATH"
	    mkdir $PV_PLUGIN_PATH
	fi
	ln -sf $FOAM_LIBBIN/libPV* $PV_PLUGIN_PATH
    else
	export PV_PLUGIN_PATH=$FOAM_LIBBIN
    fi
fi

# -----------------------------------------------------------------------------
