#!/bin/bash
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | foam-extend: Open Source CFD
#  \\    /   O peration     | Version:     4.1
#   \\  /    A nd           | Web:         http://www.foam-extend.org
#    \\/     M anipulation  | For copyright notice see file Copyright
#------------------------------------------------------------------------------
# License
#     This file is part of foam-extend.
#
#     foam-extend is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by the
#     Free Software Foundation, either version 3 of the License, or (at your
#     option) any later version.
#
#     foam-extend is distributed in the hope that it will be useful, but
#     WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#     General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with foam-extend.  If not, see <http://www.gnu.org/licenses/>.
#
# Description
#    Additionnal run functions, based on the original RunFunctions file
#
# Author:
#    Martin Beaudoin, Hydro-Quebec, 2010. All rights reserved
#
#------------------------------------------------------------------------------

# Exception handler: dump the tail of the log file on error
verbose_report_on_runApplication_error()
{
   ecode=$?
   if [ "$reportOnErrorOnlyOnce" ] ; then
       echo " "
       echo " => Error running $APP_RUN..."
       echo " => Here are the last 50 lines of the log file log.$APP_RUN..."
       echo " "
       if [ -f log.$APP_RUN ] ; then
           tail -50 log.$APP_RUN
           exit $ecode;
       fi
   fi

   # Do not report again when exiting
   unset reportOnErrorOnlyOnce
}

# Variation of runApplication with exception handling
runApplicationAndReportOnError ()
{
    trap 'verbose_report_on_runApplication_error' ERR

    LOG_NAME=
    while getopts "l:" OPTFLAG ; do
        LOG_NAME=$OPTARG
        shift $((OPTIND-1)) ; OPTIND=1
    done

    APP_RUN=$1; shift
    APP_NAME=${APP_RUN##*/}

    if [ -z $LOG_NAME ] ; then
        LOG_NAME=log.$APP_NAME
    fi

    reportOnErrorOnlyOnce=1

    if [ -f $LOG_NAME ] ; then
        echo "$APP_NAME already run on $PWD: remove log file to run"
        exit 1;
    else
        echo "Running $APP_NAME on $PWD"
        $APP_RUN $* > $LOG_NAME 2>&1
    fi
}

# We force the display of a stack trace if we encounter problems
export FOAM_ABORT=1

# Symbolic links don't work on MS Windows so we make real copies
if [ "$WM_OSTYPE" = "MSWindows" ]
then
    echo "MSWindows detected -> we need to recreate symbolic links which will be actual copies of orginal files (MSWin does not support symbolic links)"
    # Symbolic links for topAir
    ln -sf "$PWD/constant/bottomAir/thermophysicalProperties" "$PWD/constant/topAir/thermophysicalProperties"
    ln -sf "$PWD/constant/bottomAir/g" "$PWD/constant/topAir/g"
    ln -sf "$PWD/constant/bottomAir/turbulenceProperties" "$PWD/constant/topAir/turbulenceProperties"
    ln -sf "$PWD/system/bottomAir/fvSolution" "$PWD/system/topAir/fvSolution"
    ln -sf "$PWD/system/bottomAir/fvSchemes" "$PWD/system/topAir/fvSchemes"
    # Symbolic links for leftSolid
    ln -sf "$PWD/system/heater/fvSchemes" "$PWD/system/leftSolid/fvSchemes"
    ln -sf "$PWD/system/heater/fvSolution" "$PWD/system/leftSolid/fvSolution"
    # Symbolic links for rightSolid
    ln -sf "$PWD/system/heater/fvSchemes" "$PWD/system/rightSolid/fvSchemes"
    ln -sf "$PWD/system/heater/fvSolution" "$PWD/system/rightSolid/fvSolution"
fi
rm -rf constant/polyMesh/sets
runApplicationAndReportOnError blockMesh
runApplicationAndReportOnError setSet -batch makeCellSets.setSet
rm constant/polyMesh/sets/*_old
runApplicationAndReportOnError setsToZones -noFlipMap
runApplicationAndReportOnError splitMeshRegions -cellZones
cp 0/* 0.001/bottomAir/
cp 0/* 0.001/heater/
cp 0/* 0.001/leftSolid/
cp 0/* 0.001/rightSolid/
cp 0/* 0.001/topAir/
runApplication changeDictionary -region bottomAir
mv log.changeDictionary log.changeDictionary_bottomAir
runApplication changeDictionary -region topAir
mv log.changeDictionary log.changeDictionary_topAir
runApplication changeDictionary -region heater
mv log.changeDictionary log.changeDictionary_heater
runApplication changeDictionary -region leftSolid
mv log.changeDictionary log.changeDictionary_leftSolid
runApplication changeDictionary -region rightSolid
mv log.changeDictionary log.changeDictionary_rightSolid
runApplicationAndReportOnError chtMultiRegionFoam



