#!/bin/tcsh

# Check for proper number of command line args.                                                                                                               
if ($#argv != 2) then
  echo "Usage: makeLinks fluidCase solidCase"
  goto done
endif

cd $1


cd constant

ln -s ../../$2/constant solid

cd ../system

ln -s ../../$2/system solid

cd ../0

ln -s ../../$2/0 solid

cd ../../



