#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="mdEquilibrationFoam"

cd periodicCube
    runApplication blockMesh
    runApplication molConfig
    runApplication $application
cd ..

