#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name from directory
application="viscoElasticSolidFoam"

runApplication fluent3DMeshToFoam compressionRelaxationTest.msh
runApplication changeDictionary
runApplication $application