#!/bin/sh

cd PTT-Exponential
   ./Allrun

cd ..
cd DCPP
   ./Allrun

cd ..
cd Giesekus
   ./Allrun


cd ..
cd FENE-CR
   ./Allrun

cd ..
cd FENE-P
   ./Allrun

cd ..
cd Feta-PTT
   ./Allrun

cd ..
cd Leonov
   ./Allrun

cd ..
cd Oldroyd-B
   ./Allrun

cd ..
cd S-MDCPP
   ./Allrun

cd ..
cd PTT-Linear
   ./Allrun

cd ..
cd White-Metzner/Carreau-Yasuda
   ./Allrun

cd ../..
cd XPP_DE
   ./Allrun

cd ..
cd XPP_SE
   ./Allrun

cd ..
