#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

#cleanCase
cleanTimeDirectories
#\rm -f constant/polyMesh/boundary
#\rm -rf constant/polyMesh/[c-z]*
\rm -rf history
\rm -f *.ps
\rm -f *.pdf
\rm -rf forces
\rm -rf VTK

cd ../solid

#cleanCase
cleanTimeDirectories
#\rm -f constant/polyMesh/boundary
#\rm -rf constant/polyMesh/[c-z]*
\rm -f *.ps
\rm -f *.pdf

cd ..

./removeSerialLinks fluid

wclean writeFsiData

cd fluid
