#!/bin/tcsh

cd $1

cd constant

ln -s ../../$2/constant solid

cd ../system

ln -s ../../$2/system solid

cd ../0

ln -s ../../$2/0 solid

cd ..


foreach proc(processor*)
cd $proc
cd 0
ln -s ../../../$2/$proc/0 solid
cd ../constant
ln -s ../../../$2/$proc/constant solid
cd ../..
end
