#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="cavitatingFoam"

refineMeshByCellSet()
{
    echo "creating cell set for primary zone - $1"
    cp system/cellSetDict.$1 system/cellSetDict
    cellSet > log.cellSet.$1 2>&1

    echo "refining primary zone - $1"
    refineMesh -dict -overwrite > log.refineMesh.$1 2>&1
}

runApplication blockMesh

refineMeshByCellSet 1

refineMeshByCellSet 2

refineMeshByCellSet 3

runApplication $application
