#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso conjugateHeatTransfer

wmake blockCoupledScalarTransportFoam
wmake conjugateHeatFoam
wmake conjugateHeatSimpleFoam
wmake pUCoupledFoam
wmake pUCoupledFullPicardFoam
wmake pUCoupledSemiPicardFoam
# ----------------------------------------------------------------- end-of-file
