#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf VTK log*
rm -rf constant/polyMesh/points* \
    constant/polyMesh/face* \
    constant/polyMesh/owner* \
    constant/polyMesh/neighbour* \
    constant/polyMesh/*Zones* \
    constant/polyMesh/sets
