#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="icoDyMFoam"

runApplication blockMesh
runApplication setSet -batch setBatch
runApplication regionCellSets
runApplication setsToZones -noFlipMap
runApplication decomposePar
# # runApplication $application
runParallel icoDyMFoam 4
