#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="icoDyMFoam"

runApplication blockMesh
cp constant/polyMesh/boundary.org constant/polyMesh/boundary
runApplication setSet -batch setBatch
runApplication regionCellSets
runApplication setsToZones -noFlipMap
runApplication decomposePar
# # runApplication $application
runParallel icoDyMFoam 4
