#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
\rm -f .setSet constant/cellDecomposition constant/cellDecomposition.gz
\rm -rf constant/polyMesh/
\rm -rf 0 holeTri*
cp -r save 0
