#!/bin/sh
set -x

# update OpenFOAM version strings if required
wmakePrintBuild -check || /bin/rm -f OpenFOAM/Make/$WM_OPTIONS/global.? 2>/dev/null

wmakeLnInclude OpenFOAM
wmakeLnInclude OSspecific/$WM_OSTYPE
Pstream/Allwmake

wmake libo  OSspecific/$WM_OSTYPE
wmake libso OpenFOAM

( cd decompositionAgglomeration && ./Allwmake )

wmake libso lagrangian/basic

wmake libso triSurface
wmake libso edgeMesh
wmake libso meshTools
wmake libso finiteVolume
wmake libso finiteArea

wmake libso lduSolvers
wmake libso dynamicMesh

( cd tetDecompositionFiniteElement ; ./Allwmake )

wmake libso fvMotionSolver
( cd  tetDecompositionMotionSolver; ./Allwmake )

wmake libso coupledMatrix
wmake libso sampling

wmake libso dynamicFvMesh
wmake libso topoChangerFvMesh
wmake libso engine

wmake libso ODE
wmake libso randomProcesses

( cd thermophysicalModels && ./Allwmake )
( cd transportModels && ./Allwmake )
( cd turbulenceModels && ./Allwmake )
( cd lagrangian && ./Allwmake )
( cd postProcessing && ./Allwmake )
( cd conversion && ./Allwmake )

wmake libso autoMesh
wmake libso errorEstimation

# ----------------------------------------------------------------- end-of-file
