#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
\rm -f .setSet
\rm -rf 0/cellDist 0/cellDist.gz constant/cellDecomposition 
\rm -rf *.vtk VTK
\rm -rf constant/polyMesh/
\rm -rf 0 holeTri*
\rm -rf surfaces
\rm -f *raw
\rm -rf logs nohup.out

mkdir constant/polyMesh
cp -r save 0
