#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="potentialFoam"

runApplication blockMesh
\cp save/boundary constant/polyMesh/boundary

\rm -rf 0
\cp -r 0_org 0

runApplication $application -writep
runApplication writeIbMasks
