#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name from directory
application="compressibleInterFoam"

runApplication blockMesh
cp 0/alpha1.org 0/alpha1
cp 0/pd.org 0/pd
runApplication setFields
runApplication $application
