#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
\rm -f constant/polyMesh/boundary
\rm -rf history

\rm -f constant/solid/polyMesh/boundary
\rm -rf constant/solid/polyMesh/[c-z]*
\rm -rf ../solid/VTK
\rm -f *.ps
\rm -f *.pdf

cd ../solid

cleanCase

cd ..

./removeSerialLinks fluid

wclean setInletVelocity

cd fluid
