#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name from directory
application="elasticNonLinTLSolidFoam"

runApplication blockMesh
runApplication $application
